name: Build Tools Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger tools
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: obot-platform/obot
          event-type: tools
          client-payload: '{"sender": "${{ github.repository }}"}'